### ISSUE TITLE
Support GitBucket4.4?

### ISSUE THREAD

**Issue by endo-takashi** [gitbucket/gitbucket-h2-backup-plugin#16]
After upgrade 4.3 to 4.4, plugin has disappeared from "Installed Plugins".
Does H2 Backup Plugin support GitBucket 4.4?

I use latest version [1.3.0](https://github.com/gitbucket-plugins/gitbucket-h2-backup-plugin/releases/tag/1.3.0).

**Comment by McFoggy** [comment]
Normally it should, I'll check.

**Comment by McFoggy** [comment]
I tested on my PC with a fresh installation and it works as expected.

![image](https://cloud.githubusercontent.com/assets/1119660/18598761/cc0f922e-7c54-11e6-971a-ee6abe6d9472.png)

Do you have errors in the log when launching GitBucket on your installation.

**Comment by endo-takashi** [comment]
@McFoggy Thank you for response.
I checked `gitbucket.out.log` below.

```
17:34:52.407 [main] ERROR gitbucket.core.plugin.PluginRegistry - Error during plugin initialization: C:\gitbucket1\plugins\gitbucket-h2-backup.jar
java.lang.IllegalStateException: Plugin version is 1.3.0, but database version is 1.0
    at gitbucket.core.plugin.PluginRegistry$.gitbucket$core$plugin$PluginRegistry$$$anonfun$6(PluginRegistory.scala:183)
    at gitbucket.core.plugin.PluginRegistry$.gitbucket$core$plugin$PluginRegistry$$$anonfun$6$adapted(PluginRegistory.scala:170)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at gitbucket.core.plugin.PluginRegistry$.initialize(PluginRegistory.scala:170)
    at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1(InitializeListener.scala:96)
    at gitbucket.core.servlet.InitializeListener.gitbucket$core$servlet$InitializeListener$$$anonfun$1$adapted(InitializeListener.scala:37)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1$$anonfun$apply$1.apply(DatabaseComponent.scala:54)
    at scala.slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:426)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$$anonfun$withTransaction$1.apply(DatabaseComponent.scala:54)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
    at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withTransaction(DatabaseComponent.scala:54)
    at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withTransaction(JdbcBackend.scala:46)
    at gitbucket.core.servlet.InitializeListener.contextInitialized(InitializeListener.scala:37)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:837)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:810)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:411)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:378)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at JettyLauncher.main(JettyLauncher.java:65)
```

And I checked VERSIONS table with h2 console.

![versions](https://cloud.githubusercontent.com/assets/12061404/18653354/382ebd4c-7f14-11e6-9182-e2ec23bba232.png)

Maybe I failed migration process on statup.

**Comment by McFoggy** [comment]
the plugin version mechanism has changed in 3.3 but it should have worked seamlessly.
@takezoe any idea please?

In your case I think it is safe to do an update directly in the db with h2 console.
Keep us informed if everything is smooth again after the update.

**Comment by endo-takashi** [comment]
@McFoggy After updated VERSIONS table manually and restart GitBucket, H2 Backup plugin is available now.
Thanks for your advice.

**Comment by McFoggy** [comment]
Glad to hear it worked.
